source 'https://github.com/CocoaPods/Specs.git'

def common_pods
	#pod 'GTMNSStringHTMLAdditions',	'~> 0.2.1'
	pod 'GTMNSStringHTMLAdditions', :git => 'https://github.com/levigroker/GTMNSStringAdditions'
end

target :ios do
	platform :ios, '7.0'
    common_pods
end

target :osx do
	platform :osx, '10.9'
    common_pods
end
